# Generated by Django 6.0.4 on 2026-04-22 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Type", models.CharField(max_length=50)),
                (
                    "Ingredients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100)
                    ),
                ),
                ("Calories", models.IntegerField()),
                ("Price", models.FloatField(max_length=20)),
            ],
        ),
    ]
