# Generated by Django 6.0.4 on 2026-04-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditems",
            name="Image_path",
            field=models.CharField(default="images/f1.png", max_length=200),
            preserve_default=False,
        ),
    ]
