# Generated by Django 6.0.4 on 2026-04-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantapp", "0002_fooditems_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditems",
            name="Type",
            field=models.CharField(
                choices=[
                    ("meat", "Meat"),
                    ("soup", "Soup"),
                    ("garnish", "Garnish"),
                    ("hot drinks", "Hot drinks"),
                    ("cold drinks", "Cold drinks"),
                    ("alcohol", "Alcohol"),
                ],
                max_length=50,
            ),
        ),
    ]
